//----- Creates tables for School...
DROP TABLE IF EXISTS SCHOOL;
CREATE TABLE SCHOOL
(
    SCHOOL_ID LONG  NOT NULL AUTO_INCREMENT,
    SCHOOL_NAME VARCHAR(255) NOT NULL,
    SCHOOL_CITY  VARCHAR(255),
    CONSTRAINT SCHOOL_PK PRIMARY KEY (SCHOOL_ID)
);



//----- Creates tables for Passport...
DROP TABLE IF EXISTS PASSPORT;
CREATE TABLE PASSPORT
(
    PASSPORT_ID LONG  NOT NULL AUTO_INCREMENT,
    PASSPORT_NUMBER  VARCHAR(255)NOT NULL,
    PASSPORT_CITY VARCHAR(255) NOT NULL,
    CONSTRAINT PASSPORT_PK PRIMARY KEY (PASSPORT_ID)
);

//----- Creates tables for Students...
DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT
(
    STUDENT_ID LONG  NOT NULL AUTO_INCREMENT,
     SCHOOL_ID LONG,
     PASSPORT_ID LONG,
    STUDENT_NAME VARCHAR(255) NOT NULL,
    STUDENT_GENDER  VARCHAR(255),
    CONSTRAINT STUDENT_PK PRIMARY KEY (STUDENT_ID),
    CONSTRAINT STUDENT_FK FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID),
    CONSTRAINT STUDENT_FK1 FOREIGN KEY (PASSPORT_ID) REFERENCES PASSPORT(PASSPORT_ID)
);





